### ISSUE TITLE
 Don't it need a signature to send a transaction?

### ISSUE THREAD

**Issue by aaananaaa** [savvysiddharth/chainpuff#1]
When I send a transaction, it has not been successful. Shouldn't I sign the transaction before publishing it? But I don't know how to import the private key of the account. Does its application scenario require blockchain? I also use quorum ibft consensus when testing.

**Comment by daemonsloth** [comment]
You won't need to sign it if the account is already unlocked at the geth node. chainPuff assumes that the account address entered in the transaction options UI is unlocked hence doesn't need a signature.
To set up nodes in the local environment, I used this [guide](https://consensys.net/docs/goquorum/en/stable/tutorials/quorum-dev-quickstart/using-the-quickstart/ ) which gave me an unlocked account at each node by default whose private keys are stored inside node directory ./data/keystore/accountPrivateKey.
I've not tried this but, you can have more accounts with the desired balance by modifying the genesis file at the start. Alternatively, you can create new accounts using [web3.eth.accounts.create](https://web3js.readthedocs.io/en/v1.2.11/web3-eth-accounts.html#create) API which will give you a new public key and private key pair.

**Comment by LaplaceMan** [comment]
Thank you very much for your reply！！

I have another question: what do Inter-txn Delay and Inter-batch Delay in the interface mean?
